version: '3.4'

networks:
  app-network:
    driver: bridge

volumes:
  SKN_db_data:
  SKN_node_modules:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/api
      - SKN_node_modules:/api/node_modules
    environment:
      - PORT
      - DB_CONNECTION
      - DB_HOST=${MONGO_HOST}
      - DB_PORT=${MONGO_PORT}
      - DB_USER=${MONGO_USER}
      - DB_PASSWORD=${MONGO_PASSWORD}
      - DB_DATABASE=${MONGO_DATABASE}
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
    ports:
      - '${PORT}:4000'
    networks:
      - app-network
  db:
    image: mongo:3.4-xenial
    restart: always
    environment:
      - MONGO_USER
      - MONGO_PASSWORD
      - MONGO_DATABASE
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
    volumes:
      - SKN_db_data:/data/db
    ports:
      - '${MONGO_PORT}:27017'
  docs:
    build:
      context: ./api
      dockerfile: .docker/apidoc/Dockerfile
    volumes:
      - ./api/doc:/usr/share/nginx/html
    environment:
      - APIDOC_PORT
    ports:
      - '${APIDOC_PORT}:80'
    networks:
      - app-network
